### ISSUE TITLE
about the training and the eval

### ISSUE THREAD

**Issue by xiaowangfeng** [Xiaoxun-Gong/DeepH-E3#12]
when i finish the training, i see the config 

To get the prediction error and predicted Hamiltonians on the twisted structures:

1. Unzip the file `Bismuth_twisted.zip`.
2. Find the configuration file `Bismuth_eval.ini`. Read the descriptions of the input variables in this configuration file.
3. These variables need to be modified by yourself: `trained_model_dir`, `output_dir`, `processed_data_dir`, `save_graph_dir`.
4. Run the command: `/path/to/deephe3-eval.py Bismuth_eval.ini` to evaluate the trained model.
5. When finished, `hamiltonians_pred.h5` will be produced under the folders of each structures under `output_dir`. There will be a `test_result.h5` file and `src` folder under `output_dir`, which can be analyzed using `deephe3-analyze.py`.'

I want to know the processed_data_dir  is different from the training  of processed_data_dir?

could you tell me?  thanks

**Comment by Xiaoxun-Gong** [comment]
In the prediction step, the goal is to get the predicted Hamiltonians of the twisted structures which are not in the training set. Therefore the `processed_data_dir` in this step should be the folder containing structures from `Bismuth_twisted.zip`.

**Comment by xiaowangfeng** [comment]
thanks，I have geted the result , now how can I  ues the hamiltonians_pred.h5 and  info.json to compare with the  hamiltonians.h5 and how to plot the energy  photo  in the paper.

**Comment by Xiaoxun-Gong** [comment]
You can use the inference utility of DeepH-pack to get the band structure and plot them. Please refer to this [link](https://github.com/mzjb/DeepH-pack/tree/main?tab=readme-ov-file#inference-with-your-model).

**Comment by xiaowangfeng** [comment]
thanks, I have finished the The entire process foe deepH,   but I see the inference.ini 
[basic]
OLP_dir = /data/run01/scv7f2x/software-scv7f2x/DeepH-pack/example/work_dir/olp/5_4
work_dir = /data/run01/scv7f2x/software-scv7f2x/DeepH-pack/example/work_dir/inference/5_4
structure_file_name = POSCAR
task = [5]
sparse_calc_config = /data/run01/scv7f2x/software-scv7f2x/DeepH-pack/example/work_dir/inference/5_4/band.json
trained_model_dir = /data/run01/scv7f2x/software-scv7f2x/DeepH-pack/example/work_dir/trained_model
restore_blocks_py = True

[interpreter]
julia_interpreter = /data/home/scv7f2x/run/julia-1.6.6/bin/julia

[graph]
radius = 9.0
create_from_DFT = True  

I don‘t know where is the band.json for the deepH-E3 and  I only got the info.json and the hamiltonians_pred.h5. 

Please tell me how to modify the inference.ini to plot the figure.

thanks again

**Comment by Xiaoxun-Gong** [comment]
When you diagonalize the Hamiltonian using DeepH-pack, you will get `openmx.Band` file under `work_dir`, containing the band structure information in OpenMX format. This [script](https://github.com/Xiaoxun-Gong/DeepH-E3/blob/main/visual_tools/plot_band.py) takes in information from `openmx.Band` to plot the band structure. You need to put this script under `work_dir` and run `python3 plot_band.py -u <plot_upper_limit> -d <plot_lower_limit>`.

**Comment by dongsh0320** [comment]
Hi developer,
After reading your answer, I tried to use `plot_band.py` in E3 codes to plot band for DeepH-pack example for Bi. However I got the following error.

$ python3 plot_band.py 
Traceback (most recent call last): 
  File "/example/work_dir/inference/5_4/plot_band.py", line 489, in <module>
    main()
  File "/example/work_dir/inference/5_4/plot_band.py", line 485, in main
    band()
  File "/example/work_dir/inference/5_4/plot_band.py", line 477, in band
    band_plot(band_data_obj, plot_args)
  File "/example/work_dir/inference/5_4/plot_band.py", line 390, in band_plot
    hsk_coords = band_data_obj.band_data["hsk_coords"]
KeyError: 'hsk_coords'

The content in inference dirtory is in the following picture.
![content in inference](https://github.com/user-attachments/assets/7bb650a1-1ad1-4a94-8da7-1e36fcfde07f)

Looking forward to your reply. Thank you a lot.
