### ISSUE TITLE
Error occurred while running the command

### ISSUE THREAD

**Issue by liee2333** [Xiaoxun-Gong/DeepH-E3#20]
hi. the developer of DeepH-E3. When I run the preprocessing script, I encountered the following error. I have checked the relevant Python packages and they are the same as required. I would like to know what might be causing this issue and look forward to your reply.
![Uploading 微信图片_20241212133026.png…]()

**Comment by liee2333** [comment]
python /share/home/liyuting/ytl/DeepH-E3/deephe3-preprocess.py preprocess.ini
cdTraceback (most recent call last):
  File "/share/home/liyuting/ytl/DeepH-E3/deephe3-preprocess.py", line 28, in <module>
    from deephe3 import DeepHE3Kernel
  File "/share/home/liyuting/ytl/DeepH-E3/deephe3/__init__.py", line 7, in <module>
    from .kernel import DeepHE3Kernel
  File "/share/home/liyuting/ytl/DeepH-E3/deephe3/kernel.py", line 16, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/share/home/liyuting/anaconda3/envs/e3/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

**Comment by Xiaoxun-Gong** [comment]
Please run the command `pip install setuptools==59.5.0` to install the latest version of `distutils`.

**Comment by liee11-bit** [comment]
Thanks for you answer, the question has been resolved!
