### ISSUE TITLE
The error :  self.dataset_info == net_out_info_o.dataset_info means?

### ISSUE THREAD

**Issue by newplay** [Xiaoxun-Gong/DeepH-E3#9]
Dear developer,

I am attempting to replicate the 'Monolayer-MoS2' demo, and during the evaluation process, I encountered an error with the message `self.dataset_info == net_out_info_o.dataset_info`. The complete error traceback is as follows:
```bash
Traceback (most recent call last):
  File "/home/zjlin/DeepH-E3/deephe3-eval.py", line 29, in <module>
    kernel.eval(args.config, debug=args.debug)
  File "/home/zjlin/DeepH-E3/deephe3/kernel.py", line 373, in eval
    net: Net = self.load_model(os.path.join(model_path, 'src'), device=eval_config.device)
  File "/home/zjlin/DeepH-E3/deephe3/kernel.py", line 559, in load_model
    assert self.dataset_info == net_out_info_o.dataset_info
AssertionError
```
Upon inspecting the source code in `kernel.py`, I noticed that the information comes from the `model_path/src/` directory. The content of the `dataset_info.json` file is as follows:
```bash
{"spinful": false, "index_to_Z": [16, 42], "orbital_types": [[0, 0, 1, 1, 2], [0, 0, 0, 1, 1, 2, 2]]}
```
The `target_blocks.json` is assumed to be correct, so I haven't provided the details.

I identified the lines where the error originates:
```python
    def load_model(self, src_path, device='cpu'):
        assert os.path.isdir(src_path)
        sys.path.append(src_path)
        
        # load dataset_info and net_out_info
        net_out_info_o = NetOutInfo.from_json(src_path)
        if self.dataset_info is None:
            self.dataset_info = net_out_info_o.dataset_info
        else:
            assert self.dataset_info == net_out_info_o.dataset_info
        if self.net_out_info is None:
            self.net_out_info = net_out_info_o
        else:
            assert self.net_out_info == net_out_info_o
```
So, does this imply that the `dataset_info` from the model I trained is same as the dataset I intend to evaluate?

**Comment by Xiaoxun-Gong** [comment]
Yes, these lines in the code are to ensure that the user isn't trying to evaluate the model on materials that are not compatible with it. This is because the neural network model depends on specific details of the material, including atom types, "spinful", and angular momenta of atomic orbitals. Regarding your problem, what material are you trying to evaluate your model on? Please check these three properties and make sure they are the same as those specified in the `dataset_info.json` under `model_path/src/`.

**Comment by newplay** [comment]
I used the Monolayer_MoS2_Demo from your database to compare Openmx and DeepH-E3. When I ran a simple MoS2 example(unit cell), I encountered this error. However, when I ran the example for a 2x2 supercell of MoS2, it ran successfully. I initially thought you wanted to avoid potential issues arising from the accuracy of results due to pre-training in the training data (such as the correct law being overemphasized because it has been trained), but it seems I was mistaken.

**Comment by Xiaoxun-Gong** [comment]
Can you let me see the input file to the OpenMX calculation of the unit cell?

**Comment by newplay** [comment]
Sorry for my delayed response. Here is the content of the 'openmx_in.dat' file:
```=bash
##################################################
System.Name                       MoS2
DATA.PATH                         /home/zjlin/openmx3.9/DFT_DATA19
HS.fileout                        on

Species.Number                    2
<Definition.of.Atomic.Species
  Mo  Mo7.0-s3p2d2 Mo_PBE19
  S  S7.0-s2p2d1 S_PBE19
Definition.of.Atomic.Species>
Atoms.Number                      3
Atoms.SpeciesAndCoordinates.Unit  FRAC
<Atoms.SpeciesAndCoordinates
   1  Mo      0.3333329856   0.6666669846   0.3719750881           7.0    7.0    0.0  0.0  0.0  0.0  0
   2  S       0.6666669848   0.3333329858   0.4502193077           3.0    3.0    0.0  0.0  0.0  0.0  0
   3  S       0.6666669848   0.3333329858   0.2937308686           3.0    3.0    0.0  0.0  0.0  0.0  0
Atoms.SpeciesAndCoordinates>

Atoms.UnitVectors.Unit            Ang
<Atoms.UnitVectors
    3.1903159618000001    0.0000000000000000    0.0000000000000000
   -1.5951581104000001    2.7628940436999998    0.0000000000000000
    0.0000000000000000    0.0000000000000000   20.0000000000000000
Atoms.UnitVectors>

scf.XcType                        GGA-PBE   # LDA/LSDA-CA/LSDA-PW/GGA-PBE
scf.ElectronicTemperature         0.0     # default=300 (K) SIGMA in VASP
scf.energycutoff                  300       # default=150 (Ry = 13.6eV)
scf.maxIter                       2000
scf.EigenvalueSolver              Band      # DC/DC-LNO/Krylov/ON2/Cluster/Band
scf.Kgrid                         6  6  1
scf.criterion                     4e-08     # (Hartree = 27.21eV)
scf.partialCoreCorrection         on

scf.SpinPolarization              off
scf.SpinOrbit.Coupling            off

scf.Mixing.Type                   RMM-DIISK
scf.Init.Mixing.Weight            0.3
scf.Mixing.History                30
scf.Mixing.StartPulay             6
scf.Mixing.EveryPulay             1

1DFFT.EnergyCutoff                3600
1DFFT.NumGridK                    900
1DFFT.NumGridR                    900

scf.ProExpn.VNA                   off

MD.Type                           Nomd      # Nomd (SCF) / NVT_NH (MD)
Band.dispersion                 on
Band.Nkpath                     3
<Band.kpath
30 0.000 0.000 0.000 0.500 0.000 0.000 \Gamma M
30 0.500 0.000 0.000 0.333333333 0.333333333 0.000 \M K
30 0.333333333 0.333333333 0.000 0.000 0.000 0.000 \K Gamma
Band.kpath>


### END ###
########################################
```
Additionally, the training dataset is from the original database in your connection,  [Database 1](<https://zenodo.org/records/7553640/>)
Best regards,
TzuChing

**Comment by Xiaoxun-Gong** [comment]
I tried running a test calculation using your input file and I didn't find any problem with DeepH-E3, except that I changed the `System.Name` entry in your input file from `MoS2` to `openmx`. This is because DeepH-E3 parses `openmx.scfout` file to get Hamiltonian and overlap matrices by default. And do not forget to run `cat openmx.out >> openmx.scfout` before running DeepH-E3. If the problem still persists, please let me know.

**Comment by newplay** [comment]
Thank you for your assistance. I will attempt this case again. I believe you are correct; I forgot to execute `cat openmx.out >> openmx.scfout` before `get overlap-matrix` and `evalue` by DeepH-E3.

**Comment by liee11-bit** [comment]
> I tried running a test calculation using your input file and I didn't find any problem with DeepH-E3, except that I changed the `System.Name` entry in your input file from `MoS2` to `openmx`. This is because DeepH-E3 parses `openmx.scfout` file to get Hamiltonian and overlap matrices by default. And do not forget to run `cat openmx.out >> openmx.scfout` before running DeepH-E3. If the problem still persists, please let me know.

Dear developer,
      I used openmx_overlap_only to calculate the overlap matrix for inference. After the first step, I got these files:
```
band.json   element.dat                       info.json  orbital_types.dat  rlat.dat
config.ini  HGraph-TBB-rFromDFT-edge=Aij.pkl  lat.dat    overlaps.h5        site_positions.dat
```
But when I ran the inference, I encountered the same error:
```
Traceback (most recent call last):
  File "/share/home/liyuting/ytl/DeepH-E3/deephe3-eval.py", line 29, in <module>
    kernel.eval(args.config, debug=args.debug)
  File "/share/home/liyuting/ytl/DeepH-E3/deephe3/kernel.py", line 373, in eval
    net: Net = self.load_model(os.path.join(model_path, 'src'), device=eval_config.device)
  File "/share/home/liyuting/ytl/DeepH-E3/deephe3/kernel.py", line 558, in load_model
    assert self.dataset_info == net_out_info_o.dataset_info
AssertionError
```
My openmx input file configuration is as follows:
```
more openmx_in.dat 
#
#      File Name      
#

System.CurrrentDirectory         ./    # default=./
System.Name                     openmx
DATA.PATH            /share/home/liyuting/ytl/DFT_caculate/openmx/openmx3.9/DFT_DATA19  # default=../DFT_DATA19
level.of.stdout                   1    # default=1 (1-3)
level.of.fileout                  1    # default=1 (0-2)
HS.fileout                   on       # on|off, default=off

#
# SCF or Electronic System
#

scf.XcType                        GGA-PBE   # LDA/LSDA-CA/LSDA-PW/GGA-PBE
scf.ElectronicTemperature         300.0     # default=300 (K) SIGMA in VASP
scf.energycutoff                  300       # default=150 (Ry = 13.6eV)
scf.maxIter                       2000
scf.EigenvalueSolver              Band      # DC/DC-LNO/Krylov/ON2/Cluster/Band
scf.Kgrid                         1  1  1
scf.criterion                     4e-08     # (Hartree = 27.21eV)
scf.partialCoreCorrection         on

scf.SpinPolarization              nc
scf.SpinOrbit.Coupling            on

scf.Mixing.Type                   RMM-DIISK
scf.Init.Mixing.Weight            0.3
scf.Mixing.History                30
scf.Mixing.StartPulay             6
scf.Mixing.EveryPulay             1

1DFFT.EnergyCutoff                3600
1DFFT.NumGridK                    900
1DFFT.NumGridR                    900

scf.ProExpn.VNA                   off

MD.Type                           Nomd      # Nomd (SCF) / NVT_NH (MD)

Band.dispersion                 on
Band.Nkpath                     3
<Band.kpath
20 0.666666667 0.333333333 0.000  0.000 0.000 0.000  K \Gamma
20 0.000 0.000 0.000  0.500 0.000 0.000  \Gamma M
15 0.500 0.000 0.000  0.333333333 -0.333333333 0.000  M K'
Band.kpath>
#

#
# Definition of Atomic Species
#
Species.Number       1
<Definition.of.Atomic.Species
Bi   Bi8.0-s3p2d2f1       Bi_PBE19
Definition.of.Atomic.Species>

#
# Atoms
#
Atoms.Number        1116
Atoms.SpeciesAndCoordinates.Unit   Ang # Ang|AU
<Atoms.SpeciesAndCoordinates           # Unit=Ang.
  1  Bi   1.7479486   1.7572410   5.1567150   7.50   7.50
  2  Bi  21.7301732  30.0747031   5.1567150   7.50   7.50
  3  Bi  25.3633050  42.6602417   5.1567150   7.50   7.50...
```
I want to know what caused this problem.Looking forward to your help.

**Comment by Xiaoxun-Gong** [comment]
Hi, this error message means dataset info mismatch, which might happen if you want to predict on a structure that is incompatible with the dataset used to train the network. Please check the structure information including spin, orbital types (the Bi8.0-s3p2d2f1 entry), and species of ions.

**Comment by liee11-bit** [comment]
> 嗨，此错误消息表示数据集信息不匹配，如果您想在与用于训练网络的数据集不兼容的结构上进行预测，则可能会发生这种情况。请检查结构信息，包括自旋、轨道类型（Bi8.0-s3p2d2f1 条目）和离子种类。

Thanks for your help. I found that the orbital types of the inference structure were incompatible with those of the dataset used to train the network. Now, this issue has been resolved.

**Comment by liee11-bit** [comment]
> Hi, this error message means dataset info mismatch, which might happen if you want to predict on a structure that is incompatible with the dataset used to train the network. Please check the structure information including spin, orbital types (the Bi8.0-s3p2d2f1 entry), and species of ions.

Thanks for your help. I found that the orbital types of the inference structure were incompatible with those of the dataset used to train the network. Now, this issue has been resolved.
